version: "3"
services:
  redis:
    image: redis
    restart: always

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    restart: always

  s3:
    image: lphoward/fake-s3
    ports:
      - "4569:4569"
    volumes:
      - ./data/fakes3:/fakes3_root
    restart: always
  
  outline:
    image: zacharyjia/outline
    command: yarn start
    build:
      context: .
      dockerfile: Dockerfile
      args:
        pull: 1
    restart: always
    ports:
      - "9000:3000"
    environment:
      PGSSLMODE: disable
    volumes:
      - .env:/opt/outline/.env
    depends_on:
      - postgres
      - redis
      - s3
    links:
      - postgres
      - redis
      - s3
